# Generated by Django 4.2.8 on 2024-01-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ("-modified_at",)},
        ),
    ]
